kind: Pod
apiVersion: v1
metadata:
  annotations:
    app: test-application
spec:
  restartPolicy: Always
  serviceAccountName: default
  securityContext:
    seLinuxOptions:
      level: 's0:c31,c20'
    fsGroup: 1000970000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: container
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000970000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: Always
      volumeMounts:
        - name: html-storage
          mountPath: /data2
        - name: data-storage
          mountPath: /data1
      image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
  serviceAccount: default
  volumes:
    - name: html-storage
      persistentVolumeClaim:
        claimName: pvc1-html
    - name: data-storage
      persistentVolumeClaim:
        claimName: pvc1-data
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-application
  namespace: demo-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-application
  template:
    metadata:
      labels:
        app: test-application
    spec:
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: data1
      - name: data2
        persistentVolumeClaim:
        claimName: data2
      containers:
        - name: container
          volumeMounts:
          - name: data1
            mountPath: /data2
          - name: data2
            mountPath: /data2
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600